#!/usr/bin/env python3
import argparse, html.parser, urllib.request, re, heapq, json, os, tempfile, datetime
BASE='http://n2mh-web.local.mesh/mpadmin/'
class P(html.parser.HTMLParser):
 def __init__(self): super().__init__(); self.rows=[]; self.r=None; self.c=False; self.buf=[]
 def handle_starttag(self,t,a):
  if t=='tr': self.r=[]
  elif self.r is not None and t in ('td','th'): self.c=True; self.buf=[]
 def handle_data(self,d):
  if self.r is not None and self.c: self.buf.append(d)
 def handle_endtag(self,t):
  if t in ('td','th') and self.r is not None and self.c: self.r.append(' '.join(''.join(self.buf).split())); self.c=False
  elif t=='tr' and self.r is not None:
   if self.r: self.rows.append(self.r)
   self.r=None
def rows(path):
 p=P(); p.feed(urllib.request.urlopen(BASE+path,timeout=20).read().decode('utf-8','replace')); return p.rows
def digits(s): return re.sub(r'[^0-9]','',s)
def shortest(g,start,target,banned):
 q=[(0,start,[start])]; seen={}
 while q:
  d,u,path=heapq.heappop(q)
  if u in seen and seen[u] <= d: continue
  seen[u]=d
  if u==target: return path
  for v in g.get(u,[]):
   if v in banned or v in path: continue
   heapq.heappush(q,(d+1,v,path+[v]))
 return None
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--config',default='/opt/meshphone-router/peers.json'); ap.add_argument('--output',required=True); args=ap.parse_args()
 cfg=json.load(open(args.config)); local=str(cfg['local_office']); peers=cfg['peers']
 dr=rows('meshphone_dial-plan_list.php'); tr=rows('meshphone_trunks_list.php')
 g={}
 for r in tr[1:]:
  if len(r)<2: continue
  a,b=digits(r[0]),digits(r[1])
  if a and b: g.setdefault(a,set()).add(b); g.setdefault(b,set()).add(a)
 graph={k:sorted(v) for k,v in g.items()}
 records=[]; seen=set()
 for r in dr[1:]:
  if len(r)<6: continue
  office=digits(r[0]); trans=r[5].strip()
  if not office or not trans or trans in seen: continue
  seen.add(trans); records.append((office,trans))
 ext='$'+'{EXTEN}'; ds='$'+'{DIALSTATUS}'
 out=['; Generated by meshphone-routebuilder; do not edit.', '; Source: n2mh-web.local.mesh admin lists', '[MeshPhone]']
 direct=sorted([n for n in peers if peers[n].get('enabled') and n in graph.get(local,[])])
 for office,trans in records:
  if trans.startswith('_'+local[:3]):
   out.append('exten => '+trans+',1,Goto(from-internal,'+ext+':3,1)')
   continue
  candidates=[]
  for first,info in peers.items():
   if not info.get('enabled') or first not in graph.get(local,[]): continue
   path=shortest(graph,first,office,{local})
   if path: candidates.append((len(path),first,info.get('peer','')))
  candidates.sort(key=lambda x:(x[0],x[1]))
  if not candidates:
   out.append('exten => '+trans+',1,Goto(Utilities,Sorry,1)'); continue
  for i,(_,first,peer) in enumerate(candidates):
   if not peer: continue
   if i==0: out.append('exten => '+trans+',1,Dial(IAX2/'+peer+'/'+ext+',10)')
   else: out.append(' same => n(try'+str(i)+'),Dial(IAX2/'+peer+'/'+ext+',10)')
   if i < len(candidates)-1:
    nxt='try'+str(i+1)
    out.append(' same => n,GotoIf($["'+ds+'"="CHANUNAVAIL" || "'+ds+'"="CONGESTION" || "'+ds+'"="NOANSWER"]?'+nxt+':done)')
   else:
    out.append(' same => n,GotoIf($["'+ds+'"="CHANUNAVAIL" || "'+ds+'"="CONGESTION" || "'+ds+'"="NOANSWER"]?sorry:done)')
  out.append(' same => n(sorry),Goto(Utilities,Sorry,1)')
  out.append(' same => n(done),Hangup()')
 out.append('; records='+str(len(records))+' graph_nodes='+str(len(graph))+' graph_edges='+str(sum(len(v) for v in graph.values())//2))
 os.makedirs(os.path.dirname(args.output),exist_ok=True)
 fd,tmp=tempfile.mkstemp(prefix='.meshphone-',dir=os.path.dirname(args.output),text=True)
 with os.fdopen(fd,'w') as f: f.write('\n'.join(out)+'\n')
 os.replace(tmp,args.output)
 print('records='+str(len(records))+' graph_nodes='+str(len(graph))+' graph_edges='+str(sum(len(v) for v in graph.values())//2)+' direct_peers='+','.join(direct)+' output='+args.output)
if __name__=='__main__': main()
